[postgres]
host = "a2ei-data.fritz.box"
port = 5432
dbname = "a2ei-data"
user = "postgres"
password = "34yN4E4hky5wywh"

[aws]
host = "a2ei-data.cuusvu0bvdq2.eu-central-1.rds.amazonaws.com"
port = 5432
dbname = "a2ei-data"
user = "postgres"
password = "34yN4E4hky5wywh"
